name: Builder

on:
  push:
    branches:
      - main
      - ci


jobs:
  docker-ci-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
          docker pull 'docker.pkg.github.com/kbeckmann/ubuntubuilder/ubuntubuilder-arm'
          docker tag docker.pkg.github.com/kbeckmann/ubuntubuilder/ubuntubuilder-arm:latest ubuntubuilder-arm
          docker run --rm -v $(pwd):/build -w /build ubuntubuilder-arm sudo -E ./.ci_build_ubuntu.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-ci-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./.ci_build_macos.sh

  docker-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -f Dockerfile --tag kbeckmann/retro-go-builder .
